image: registry.gitlab.com/wearesmile/glass:latest
variables:
  PROJECT_TYPE: "plugins"
cache:
  paths:
  - vendor/
  - node_modules/

stages:
  - test
  - deploy

#codingstandards:
#  stage: test
#  only:
#  - testing
#  - staging
#  - production
#  script:
#  - files=$(git ls-files -om --exclude-standard '*.php')
#  - phpcs -p -s -v -n . --extensions=php --ignore=/vendor,/node_modules,/bower_components,/inc/class-tgm-plugin-activation.php $files

phplint:
  stage: test
  only:
  - testing
  - staging
  #- production
  script:
  - cd $CI_PROJECT_DIR
  - find . -type d \( -path ./vendor -o -path ./plugins \) -prune -o \( -name '*.php' \) -exec php -lf {} \;

deploy:linode:
  stage: deploy
  environment:
    name: Production
  only:
    - production
  script:
    - mkdir -p ~/.ssh
    - eval "$(ssh-agent)"
    - DIRECTORY=/srv/wearesmile.com/public_html/wp-content/plugins/border-control
    - echo "$STAGING_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - chmod 700 ~/.ssh
    - ssh -o StrictHostKeyChecking=no smile@$PRODUCTION_IP uptime
    - if ssh -p22 smile@$PRODUCTION_IP [ ! -d "$DIRECTORY" ]; then ssh -p22 smile@$PRODUCTION_IP "mkdir $DIRECTORY"; fi
    - rsync -ravp --exclude-from=$CI_PROJECT_DIR/deploy/exclude-list.txt --delete-excluded $CI_PROJECT_DIR/ smile@$PRODUCTION_IP:$DIRECTORY
   
deploy:aws:
  stage: deploy
  environment:
    name: Production
  only:
    - production
  script:
    - zip -X -r $CI_PROJECT_NAME.zip ./$CI_PROJECT_NAME/
    - aws s3 cp ./$CI_PROJECT_NAME.zip s3://$AWS_BUCKET
    - aws ssm send-command --document-name "AWS-RunShellScript" --targets '{"Key":"tag:elasticbeanstalk:environment-id","Values":["e-dtiq79tvyu"]}' --max-concurrency "50%" --parameters '{"commands":["bash /tmp/unzip_depoy.sh '$PROJECT_TYPE' '$CI_PROJECT_NAME'"],"executionTimeout":["3600"]}' --timeout-seconds 600 --region eu-west-1