image: registry.gitlab.com/wearesmile/glass:latest

variables:
  PROJECT_TYPE: "plugins"

cache:
  paths:
  - vendor/
  - node_modules/

stages:
  - test
  - deploy

#codingstandards:
#  stage: test
#  only:
#  - testing
#  - staging
#  - production
#  script:
#  - files=$(git ls-files -om --exclude-standard '*.php')
#  - phpcs -p -s -v -n . --extensions=php --ignore=/vendor,/node_modules,/bower_components,/inc/class-tgm-plugin-activation.php $files

phplint:
  stage: test
  only:
  - testing
  - staging
  #- production
  script:
  - cd $CI_PROJECT_DIR
  - find . -type d \( -path ./vendor -o -path ./plugins \) -prune -o \( -name '*.php' \) -exec php -lf {} \;

deploy:testing:
  stage: deploy
  environment:
    name: Testing
  only:
    - testing
  script:
    - zip -X -r $CI_PROJECT_NAME.zip ../$CI_PROJECT_NAME/ --exclude $(<./deploy/exclude.txt)
    - aws s3 cp ./$CI_PROJECT_NAME.zip s3://$AWS_BUCKET-testing
    - aws ssm send-command --document-name "AWS-RunShellScript" --targets '{"Key":"tag:ec2:environment-name","Values":["testing"]}' --max-concurrency "100%" --parameters '{"commands":["bash /tmp/unzip_and_move.sh '$PROJECT_TYPE' '$CI_PROJECT_NAME'"],"executionTimeout":["3600"]}' --timeout-seconds 600 --region eu-west-2
  
deploy:aws:
  stage: deploy
  environment:
    name: Production
  only:
    - production
  script:
    - zip -X -r $CI_PROJECT_NAME.zip ../$CI_PROJECT_NAME -x *.git*
    - aws s3 cp ./$CI_PROJECT_NAME.zip s3://$AWS_BUCKET
    - aws ssm send-command --document-name "AWS-RunShellScript" --targets '{"Key":"tag:elasticbeanstalk:environment-id","Values":["e-dtiq79tvyu"]}' --max-concurrency "50%" --parameters '{"commands":["bash /tmp/unzip_and_move.sh '$PROJECT_TYPE' '$CI_PROJECT_NAME'"],"executionTimeout":["3600"]}' --timeout-seconds 600 --region eu-west-1